--- 
- name: Post-deployment tasks
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    kubeconfig : ~/.kube/config
  tasks:
    - name: Get backend pod name
      command: kubectl get pods -n default -l app=backend -o jsonpath="{.items[0].metadata.name}"
      register: backend_pod

    - name: Apply DB migrations
      include_role:
        name: init-db